blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='list_blog'),
    path('create/', never_cache(BlogCreateView.as_view()), name='create_blog'),
    path('view/<slug:slug>/', BlogDetailView.as_view(), name='view_blog'),
    path('edit/<slug:slug>/', never_cache(BlogUpdateView.as_view()), name='edit_blog'),
    path('delete/<slug:slug>/', BlogDeleteView.as_view(), name='delete_blog'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.apps import CatalogConfig
from catalog.views import *

app_name = CatalogConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('contacts/', contacts, name='contacts'),
    path('catalog/', ProductListView.as_view(), name='list_product'),
    path('catalog/create/', never_cache(ProductCreateView.as_view()), name='create_product'),
    path('catalog/view/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='view_product'),
    path('catalog/edit/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='edit_product'),
    path('catalog/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('catalog/version_create/', VersionCreateView.as_view(), name='version_create')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='catalog/', null=True, blank=True, verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='Цена за покупку')
    date_of_creation = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name='Дата создания')
    date_last_modified = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name='Дата последнего изменения')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Владелец')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name} {self.category} {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)
        permissions = [
            (
                'set_published',
                'Can publish posts'
            )
        ]


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Contacts(models.Model):
    country = models.CharField(max_length=50, verbose_name='Страна')
    inn = models.CharField(max_length=20, verbose_name='ИНН')
    address = models.CharField(max_length=100, verbose_name='Адрес')

    def __str__(self):
        return f'{self.country} {self.inn} {self.address}'

    class Meta:
        verbose_name = 'контакты'
        verbose_name_plural = 'контакты'


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='продукт')
    version_number = models.IntegerField(verbose_name='номер версии')
    version_name = models.CharField(max_length=100, verbose_name='название версии')
    is_active = models.BooleanField(default=True, verbose_name='текущая версия')

    def __str__(self):
        return f'{self.product} - {self.version_number} ({self.version_name})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from catalog.models import Product, Version

FORBIDDEN_WORDS = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Product
        fields = ('name', 'description', 'image', 'category', 'price', 'is_published')

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']
        for word in FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError('Наименование содержит запрещенные слова')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        for word in FORBIDDEN_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError('Описание содержит запрещенные слова')
        return cleaned_data


class VersionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Version
        fields = ('product', 'version_number', 'version_name', 'is_active')


class ProductFormMod(ProductForm):

    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse

from catalog.forms import ProductForm, VersionForm, ProductFormMod
from catalog.models import Contacts, Product, Version


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(name, phone, message)

    contact = Contacts.objects.get(pk=1)
    context = {
        'object_contact': contact,
        'title': 'Контакты'
    }

    return render(request, 'catalog/contacts.html', context)


def home(request):
    context = {
        'title': 'Skystore'
    }
    return render(request, 'catalog/home.html', context)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:list_product')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save
        return super().form_valid(form)


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product

    def get_form_class(self):
        if self.request.user.is_staff:
            return ProductFormMod
        return ProductForm

    def get_success_url(self):
        return reverse('catalog:view_product', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:list_product')


class VersionCreateView(LoginRequiredMixin, CreateView):
    model = Version
    form_class = VersionForm

    def get_success_url(self):
        return reverse('catalog:view_product', args=[self.object.product.pk])

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore: {{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/inc_main_menu.html' %}

{% block content %}
{% endblock %}

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/catalog.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-4">
            {% for object in object_list %}
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ object.image|mediapath }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ object.name|capfirst }}</h5>
                                <p class="card-text">{{ object.price }} руб</p>
                                <p class="card-text">{{ object.description|capfirst }}</p>
                                <p class="card-text"><small class="text-body-secondary">Последнее обновление {{ object.date_last_modified }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>{{ object_contact.country }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>{{ object_contact.inn }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>{{ object_contact.address }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Skystore - это отличный вариант покупки товаров для дома</p>
</div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6 text-center">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Удалить товар "{{ object.name }}"?</p>
                    <button type="submit" class="p-2 btn btn-outline-danger">Подтвердить</button>
                    <a href="{% url 'blog:list_blog' %}" class="p-2 btn btn-outline-success">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-5 px-5">
                <img style="max-width: 540px;" src="/media/{{ object.image }}" />
            </div>
            <div class="col-5 px-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title text-center">
                            {{ object.name|capfirst }}
                        </h3>
                        <h6 class="card-title text-center">
                            {{ object.category|capfirst }}
                        </h6>
                    </div>
                    <div class="card-body">
                        <table class="table">
                            <tr>
                                <td>Описание:</td>
                                <td>{{ object.description|capfirst }}</td>
                            </tr>
                            <tr>
                                <td>Цена:</td>
                                <td>{{ object.price }} руб</td>
                            </tr>
                            <tr>
                                <td>Дата создания:</td>
                                <td>{{ object.date_of_creation }}</td>
                            </tr>
                            <tr>
                                <td>Дата последнего изменения:</td>
                                <td>{{ object.date_last_modified }}</td>
                            </tr>
                            {% for version in object.version_set.all %}
                                {% if version.is_active %}
                                    <tr>
                                        <td>Актуальная версия:</td>
                                        <td>{{ version.version_number }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            <tr>
                                <td>Автор:</td>
                                <td>{{ object.owner }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="card-footer">
                        Просмотры {{object.views_count }}<br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="py-4 text-center">
        {% if user.is_staff or user == object.owner %}
        <a class="p-2 btn btn-outline-success" href="{% url 'catalog:edit_product' object.pk %}">Редактировать товар</a>
        {% endif %}
        {% if user == object.owner %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:version_create' %}">Создать версию товара</a>
        <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:delete_product' object.pk %}">Удалить товар</a>
        {% endif %}
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Каталог</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ object.image|mediapath }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <a href = "{% url 'catalog:view_product' object.pk %}">{{ object.name|capfirst }}</a>
                                </h5>
                                <p class="card-text">{{ object.price }} руб</p>
                                <p class="card-text">{{ object.description|capfirst }}</p>
                                <p class="card-text">
                                    <small class="text-body-secondary">
                                        {% for version in object.version_set.all %}
                                            {% if version.is_active %}
                                                Актуальная версия: {{ version.version_number }}<br>
                                            {% endif %}
                                        {% endfor %}
                                        Последнее обновление {{ object.date_last_modified }}<br>
                                        {{ object.owner }}
                                    </small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
<div class="d-grid gap-2 col-6 mx-auto">
    {% if user.is_authenticated %}
    <a class="p-2 btn btn-outline-success" href="{% url 'catalog:create_product' %}">Добавить новый товар</a>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="p-2 btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}